# Copyright (C) 2026 loteran
# SPDX-License-Identifier: GPL-3.0-or-later

"""_conf_has_bare_ladspa must see every ladspa node, however it is formatted.

A plugin referenced by bare name fails to dlopen on a host that does not have
it and takes the whole filter-chain module down — HeSuVi included (#100). This
function is what marks such a conf stale so the repair pass regenerates it with
the staged ~/.ladspa absolute path.

It used to require `type = ladspa` and `plugin =` on the *same line*. The nodes
generate_sonar_micro_conf writes for RNNoise and DeepFilterNet put them on two,
so a micro chain referencing them by bare name was never seen as stale and
never regenerated: the exact failure this function exists to catch, left open
for the one channel whose nodes happen to be formatted differently.

Found while writing the #181 diagnostic script, which scans the whole file and
therefore disagreed with production about the same conf.
"""
from __future__ import annotations

import pytest

from arctis_sound_manager.sonar_to_pipewire import _conf_has_bare_ladspa

# Exactly the shapes generate_sonar_micro_conf and generate_hesuvi_conf emit.
_TWO_LINE_BARE = (
    "                    { type = ladspa  name = rnnoise\n"
    "                      plugin = librnnoise_ladspa.so  label = noise_suppressor_mono\n"
    '                      control = { "VAD Threshold (%)" = 50.0 } }'
)
_TWO_LINE_ABSOLUTE = (
    "                    { type = ladspa  name = dfn\n"
    "                      plugin = /home/u/.ladspa/deep_filter_ladspa.so  label = deep_filter_mono\n"
    '                      control = { "Attenuation Limit (dB)" = 90.0 } }'
)
_ONE_LINE_BARE = "{ type = ladspa  name = plate_L  plugin = plate_1423  label = plate }"
_ONE_LINE_ABSOLUTE = (
    "{ type = ladspa  name = plate_L  plugin = /usr/lib64/ladspa/plate_1423.so  label = plate }"
)


@pytest.mark.parametrize("conf,expected,why", [
    (_TWO_LINE_BARE, True, "the case that was missed: RNNoise, plugin on its own line"),
    (_TWO_LINE_ABSOLUTE, False, "two lines but properly staged — nothing to repair"),
    (_ONE_LINE_BARE, True, "the case that already worked, and must keep working"),
    (_ONE_LINE_ABSOLUTE, False, "the healthy shape on a native install"),
    ("{ type = builtin  label = copy  name = copyFL }", False, "builtin nodes have no plugin"),
    ("# plugin = plate_1423 is what the old fallback wrote", False,
     "a header comment naming a plugin is documentation, not a reference"),
    ("", False, "empty conf"),
])
def test_detection(conf, expected, why):
    assert _conf_has_bare_ladspa(conf) is expected, why


def test_a_real_micro_conf_with_a_bare_rnnoise_is_caught():
    """End to end on the generator's own output shape, mixed with builtins."""
    conf = (
        "# Auto-generated by Arctis Sound Manager — DO NOT EDIT\n"
        "# ASM-CONF-VERSION: 4\n"
        "context.modules = [\n"
        "  { name = libpipewire-module-filter-chain\n"
        "    args = { filter.graph = { nodes = [\n"
        "                    { type = builtin  name = bq0  label = bq_peaking }\n"
        + _TWO_LINE_BARE + "\n"
        "    ] } } }\n"
        "]\n"
    )
    assert _conf_has_bare_ladspa(conf) is True
