# Copyright (C) 2026 loteran
# SPDX-License-Identifier: GPL-3.0-or-later

"""Issue #180 — the headset must be allowed to fall asleep.

Every node ASM puts between an application and the headset used to be an
*active* node: it pushed its chain continuously, so the physical sink sat in
RUNNING with nothing playing, the firmware never saw an idle moment, and its
auto-off timer never started. Measured on a Nova Pro Wireless: with the whole
chain passive the graph suspends and the headset powers off (45 s on a 1-minute
setting); with a single non-passive node left anywhere in it, nothing suspends.

That last part is what these tests guard. It is not enough for *most* of the
chain to be passive — one active node holds every node downstream of it, and
the device, awake. So each generator gets its own assertion rather than a
single "the fix is in" test.
"""

from pathlib import Path

import pytest

from arctis_sound_manager import sonar_to_pipewire as _s2p
from arctis_sound_manager.loopback_manager import (
    LoopbackSpec,
    _build_pw_loopback_argv,
)


def _playback_block(conf: str) -> str:
    """The playback.props block alone — the capture side must stay active."""
    match = _s2p._PLAYBACK_BLOCK_RE.search(conf)
    assert match is not None, "conf has no playback.props block"
    return match.group(1)


# ── the generators ────────────────────────────────────────────────────────────

@pytest.mark.parametrize("channel", ["game", "media", "chat", "output"])
def test_generated_eq_conf_playback_is_passive(channel: str, monkeypatch) -> None:
    monkeypatch.setattr(_s2p, "_write_conf", lambda path, text: None)
    monkeypatch.setattr(_s2p, "_get_physical_out_chat", lambda: "alsa_output.test")
    monkeypatch.setattr(_s2p, "_get_physical_out_game", lambda: "alsa_output.test")
    conf = _s2p.generate_sonar_eq_conf(
        channel, [], 0.0, 0.0, 0.0, output_path=Path("/dev/null"),
    )
    assert "node.passive" in _playback_block(conf)


def test_bypass_conf_playback_is_passive() -> None:
    conf = _s2p._bypass_conf(
        "effect_input.sonar-game-eq", "alsa_output.test", 8,
        "FL FR FC LFE RL RR SL SR", channel="game", owns_link=True,
    )
    assert "node.passive" in _playback_block(conf)


@pytest.mark.parametrize("channel", ["game", "media"])
def test_hesuvi_conf_playback_is_passive(channel: str, monkeypatch) -> None:
    monkeypatch.setattr(_s2p, "_device_attached", lambda: True)
    monkeypatch.setattr(_s2p, "_get_physical_out_game", lambda: "alsa_output.test-game")
    monkeypatch.setattr(_s2p, "_write_conf", lambda path, text: None)
    monkeypatch.setattr(_s2p, "_ladspa_plugin_ref", lambda name: None)
    conf = _s2p.generate_hesuvi_conf(output_path=Path("/dev/null"), channel=channel)
    assert "node.passive" in _playback_block(conf)


def test_loopback_playback_is_passive_but_capture_is_not() -> None:
    spec = LoopbackSpec(
        channel="media", capture_name="Arctis_Media",
        playback_name="Arctis_Media_sink_out",
        target="effect_input.sonar-media-eq", description="Arctis Media",
    )
    argv = _build_pw_loopback_argv(spec)
    capture, playback = argv[1], argv[2]
    assert "node.passive=true" in playback
    # The capture side is the sink applications play into. Passive there would
    # stop it from ever waking the chain — silence instead of a sleeping headset.
    assert "node.passive" not in capture


# ── what must NOT become passive ──────────────────────────────────────────────

def test_micro_conf_is_not_passive(monkeypatch) -> None:
    """The mic chain is an Audio/Source — the capture end, with no device to
    hold awake. Marking it passive gains nothing and risks the mic not waking."""
    monkeypatch.setattr(_s2p, "_write_conf", lambda path, text: None)
    monkeypatch.setattr(_s2p, "_get_physical_in", lambda: "alsa_input.test")
    conf = _s2p.generate_sonar_micro_conf(
        [], 0.0, 0.0, 0.0, output_path=Path("/dev/null"),
    )
    assert "node.passive" not in _playback_block(conf)


def test_micro_conf_not_in_repair_list() -> None:
    assert not any("micro" in name for name in _s2p._PASSIVE_CONFS)


# ── the in-place repair for confs written by an older ASM ─────────────────────

_OLD_CONF = """\
# Auto-generated by Arctis Sound Manager — DO NOT EDIT
# ASM-CONF-VERSION: 3
context.modules = [
  { name = libpipewire-module-filter-chain
    args = {
      filter.graph = {
        nodes = [
          { type = builtin name = eq_band_1 label = bq_peaking
            control = { Freq = 100.0 Q = 1.4 Gain = 6.0 } }
        ]
      }
      capture.props = {
        node.name      = "effect_input.sonar-game-eq"
        media.class    = Audio/Sink/Internal
      }
      playback.props = {
        node.name           = "effect_output.sonar-game-eq"
        node.dont-fallback  = true
        node.linger         = true
        audio.channels      = 8
      }
    }
  }
]
"""


def test_repair_inserts_passive(tmp_path: Path) -> None:
    conf = tmp_path / "sonar-game-eq.conf"
    conf.write_text(_OLD_CONF)
    assert _s2p._ensure_passive_playback(conf) is True
    assert "node.passive" in _playback_block(conf.read_text())


def test_repair_preserves_the_users_eq(tmp_path: Path) -> None:
    """The whole reason this is a patch and not a regeneration: nothing here
    can read back the user's bands, so a regen would flatten them."""
    conf = tmp_path / "sonar-game-eq.conf"
    conf.write_text(_OLD_CONF)
    _s2p._ensure_passive_playback(conf)
    after = conf.read_text()
    assert "Freq = 100.0 Q = 1.4 Gain = 6.0" in after
    assert "# ASM-CONF-VERSION: 3" in after
    # Exactly one line added, nothing removed.
    assert len(after.splitlines()) == len(_OLD_CONF.splitlines()) + 1


def test_repair_leaves_the_capture_side_alone(tmp_path: Path) -> None:
    conf = tmp_path / "sonar-game-eq.conf"
    conf.write_text(_OLD_CONF)
    _s2p._ensure_passive_playback(conf)
    capture = conf.read_text().split("playback.props")[0]
    assert "node.passive" not in capture


def test_repair_is_idempotent(tmp_path: Path) -> None:
    conf = tmp_path / "sonar-game-eq.conf"
    conf.write_text(_OLD_CONF)
    assert _s2p._ensure_passive_playback(conf) is True
    once = conf.read_text()
    assert _s2p._ensure_passive_playback(conf) is False
    assert conf.read_text() == once


def test_repair_on_missing_file_is_harmless(tmp_path: Path) -> None:
    assert _s2p._ensure_passive_playback(tmp_path / "nope.conf") is False


def test_repair_keeps_the_equals_aligned(tmp_path: Path) -> None:
    """The file still has to read like a generated one, not a hand edit."""
    conf = tmp_path / "sonar-game-eq.conf"
    conf.write_text(_OLD_CONF)
    _s2p._ensure_passive_playback(conf)
    lines = [ln for ln in conf.read_text().splitlines()
             if "node.linger" in ln or "node.passive" in ln]
    assert len(lines) == 2
    assert lines[0].index("=") == lines[1].index("=")


# ── the guard against the next forgotten template ─────────────────────────────

def test_every_output_template_declares_passive() -> None:
    """Scan the module source, not just the generators these tests call.

    This issue cost five rounds with the reporter because a repair list was
    written by hand and two of the six confs were left out of it — the two
    that then stayed awake. The same mistake is available to anyone adding a
    seventh template here, and no per-generator test would catch it, so this
    one reads the source and holds every playback.props block to the rule:
    passive if it feeds a device, not passive if it is the mic's Audio/Source.
    """
    import inspect
    import re

    src = inspect.getsource(_s2p)
    blocks = re.findall(r"playback\.props = \{\{(.*?)\n      \}\}", src, re.DOTALL)
    assert blocks, "no playback.props templates found — did the format change?"

    for block in blocks:
        name = re.search(r'node\.name\s+=\s+"([^"]+)"', block)
        assert name is not None, f"template with no node.name:\n{block}"
        is_micro = "micro" in name.group(1)
        has_passive = "node.passive" in block
        assert has_passive is not is_micro, (
            f"{name.group(1)}: node.passive should be "
            f"{'absent (Audio/Source)' if is_micro else 'present (feeds a device)'}"
        )
