from argparse import ArgumentParser
import os
from pathlib import Path
import subprocess
import sys
from typing import NamedTuple

from ruamel.yaml import YAML

from linux_arctis_manager.config import DeviceConfiguration
from linux_arctis_manager.constants import DEVICES_CONFIG_FOLDER, UDEV_RULES_PATH
from linux_arctis_manager.utils import project_version

ConfigRuleset = NamedTuple(
    'ConfigRuleset',
    [
        ('vendor_id', int),
        ('product_ids', list[int]),
        ('device_name', str)
    ])

def write_udev_rules(rules_path: Path, create_directories: bool, force_write: bool) -> int:
    print('Writing udev rules...')

    if rules_path.is_dir():
        print(f'Cannot write to directory {rules_path}')
        print('Please specify a file.')

        return 1
    
    if create_directories:
        rules_path.parent.mkdir(parents=True, exist_ok=True)

    if not rules_path.parent.exists():
        print(f'Cannot write to {rules_path}')
        print('Parent directory does not exist.')

        return 2

    if rules_path.exists() and not os.access(rules_path, os.W_OK) \
        or not rules_path.exists() and not os.access(rules_path.parent, os.W_OK):
        print(f'Cannot write to {rules_path}')
        print('Try executing with root privileges.')

        return 3
    
    if not force_write and rules_path.exists():
        print(f'File {rules_path} already exists.')
        print('To overwrite add option --force.')

        return 4
    
    yaml = YAML(typ='safe')
    products: dict[int, ConfigRuleset] = {}
    for config_path in DEVICES_CONFIG_FOLDER:
        for config_file in config_path.glob('*.yaml'):
            config_yaml = yaml.load(config_file)

            config = DeviceConfiguration(config_yaml)
            products[config.vendor_id] = ConfigRuleset(config.vendor_id, config.product_ids, config.name)
    
    rule_template = 'SUBSYSTEM=="usb", ENV{{DEVTYPE}}=="usb_device", ATTRS{{idVendor}}=="{idVendor}", ATTRS{{idProduct}}=="{idProducts}", TAG+="uaccess"'
    rules = []
    for vendor_id, ruleset in products.items():
        rule = rule_template.format(
            idVendor=f'{vendor_id:04x}',
            idProducts='|'.join([f'{pid:04x}' for pid in ruleset.product_ids]) if len(ruleset.product_ids) > 1 else f'{ruleset.product_ids[0]:04x}'
        )
        rules.extend(['', f'# {ruleset.device_name}', rule])

    with rules_path.open('w') as f:
        f.write('# Generated by Arctis Manager via lam-cli udev write-rules\n\n')
        f.write('ACTION=="remove", GOTO="local_end"\n')
        f.write('\n'.join(rules))
        f.write('\n\nLABEL="local_end"\n')
    
    return 0

def reload_udev_rules() -> int:
    if os.geteuid() != 0:
        print('Please run the command with sudo / as root.')

        return 1
    
    print('Reloading udev rules...')

    result = subprocess.run(["udevadm", "control", "--reload-rules"], check=True)
    if result.returncode != 0:
        return result.returncode

    result = subprocess.run(["udevadm", "trigger", "--subsystem-match=usb"], check=True)

    if result.returncode == 0:
        print('Udev rules reloaded.')
    else:
        print('Failed to reload udev rules.')

    return result.returncode

def main():
    parser = ArgumentParser(description=f'Arctis Manager CLI v {project_version()}')
    subparsers = parser.add_subparsers(dest='command', required=True)

    udev_parser = subparsers.add_parser('udev', help='UDEV rules')
    udev_subparsers = udev_parser.add_subparsers(dest='action', required=True)

    write_parser = udev_subparsers.add_parser('write-rules', help='Write the udev rules')
    write_parser.add_argument('--rules-path', default=UDEV_RULES_PATH, type=Path)
    write_parser.add_argument('--create-directories', action='store_true')
    write_parser.add_argument('--force', action='store_true')
    write_parser.add_argument('--reload', action='store_true')

    reload_parser = udev_subparsers.add_parser('reload-rules', help='Reload the udev rules')

    args = parser.parse_args()

    if not hasattr(args, 'action'):
        parser.print_help()
        return

    if args.command == 'udev':
        if args.action == 'write-rules':
            result = write_udev_rules(args.rules_path, args.create_directories, args.force)
            if result != 0:
                sys.exit(result)
            if args.reload:
                sys.exit(reload_udev_rules())
        elif args.action == 'reload-rules':
            sys.exit(reload_udev_rules())
