# Copyright (C) 2026 loteran
# SPDX-License-Identifier: GPL-3.0-or-later

"""
pw_quirks.py — Per-device WirePlumber hardware quirks.

Some Arctis devices need a small WirePlumber ALSA monitor rule to work
around a hardware/USB quirk. Currently the only quirk is the ALSA capture
headroom override for the Nova Pro Wireless (issue #105): its USB playback
SYNC endpoint has no explicit feedback, which produces audible crackle on
some systems unless ``api.alsa.headroom`` is raised.

The quirk is expressed per-device via the optional ``alsa_headroom`` key in
the device YAML (see ``config.DeviceConfiguration.alsa_headroom``) and
applied here by writing a WirePlumber ``.conf.d`` fragment. WirePlumber is
restarted — never the whole PipeWire stack — and only when the fragment's
content actually changed, to avoid disrupting active audio streams on every
device (re)attach.
"""
from __future__ import annotations

import logging
import re
import subprocess
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from arctis_sound_manager.config import DeviceConfiguration

_log = logging.getLogger(__name__)

_WP_CONF_DIR = Path.home() / ".config" / "wireplumber" / "wireplumber.conf.d"
_HEADROOM_CONF_NAME = "91-asm-alsa-headroom.conf"

# The `monitor.alsa.rules` .conf.d syntax used below requires WirePlumber's
# Lua5 config engine, shipped since 0.5. Older WirePlumber (0.4.x) uses a
# different config format entirely — skip rather than write a fragment it
# can't parse.
_MIN_WIREPLUMBER_VERSION = (0, 5)


def _wireplumber_version() -> tuple[int, int] | None:
    """Return the installed WirePlumber's (major, minor) version, or None if
    the binary is missing or its output could not be parsed."""
    try:
        result = subprocess.run(
            ["wireplumber", "--version"],
            capture_output=True, text=True, timeout=5,
        )
    except (FileNotFoundError, OSError, subprocess.TimeoutExpired) as exc:
        _log.info("pw_quirks: could not run 'wireplumber --version' (%s)", exc)
        return None

    output = (result.stdout or "") + (result.stderr or "")
    match = re.search(r"(\d+)\.(\d+)", output)
    if not match:
        _log.info("pw_quirks: could not parse WirePlumber version from %r", output.strip())
        return None
    return int(match.group(1)), int(match.group(2))


def _render_headroom_conf(headroom: int) -> str:
    return (
        "# Auto-generated by Arctis Sound Manager — DO NOT EDIT\n"
        "# ALSA headroom quirk (issue #105): the device's USB SYNC endpoint has\n"
        "# no explicit feedback, which can produce audible crackle. Raising\n"
        "# api.alsa.headroom compensates for the missing feedback.\n"
        "monitor.alsa.rules = [\n"
        "  { matches = [\n"
        "      { node.name = \"~alsa_output.*SteelSeries.*\" }\n"
        "    ]\n"
        "    actions = {\n"
        f"      update-props = {{ api.alsa.headroom = {headroom} }}\n"
        "    }\n"
        "  }\n"
        "]\n"
    )


def apply_alsa_headroom_quirk(device_config: "DeviceConfiguration") -> bool:
    """Write, update or remove the WirePlumber ALSA headroom quirk fragment for
    *device_config*.

    - ``device_config.alsa_headroom is None`` → remove the fragment if present
      (cleanup: e.g. the previously-attached device needed the quirk, the
      newly-attached one doesn't).
    - otherwise → write/update the fragment with that headroom value.

    WirePlumber is restarted via :mod:`service_control` (never plain
    ``systemctl``/``dinitctl`` and never the full PipeWire stack) only when
    the fragment's content actually changed on disk. Requires WirePlumber
    >= 0.5 for the fragment's Lua5 syntax; older/undetectable versions are
    skipped with an info log (no fragment is written, nothing is removed
    beyond what a missing-quirk cleanup already does).

    Returns True if a change was made on disk (and WirePlumber was
    restarted), False otherwise.
    """
    conf_path = _WP_CONF_DIR / _HEADROOM_CONF_NAME
    headroom = getattr(device_config, "alsa_headroom", None)

    if headroom is None:
        return _remove_headroom_conf(conf_path)

    version = _wireplumber_version()
    if version is None or version < _MIN_WIREPLUMBER_VERSION:
        _log.info(
            "pw_quirks: ALSA headroom quirk requires WirePlumber >= %s "
            "(detected: %s) — skipping.",
            ".".join(map(str, _MIN_WIREPLUMBER_VERSION)), version,
        )
        return False

    new_content = _render_headroom_conf(headroom)
    old_content = conf_path.read_text() if conf_path.exists() else None
    if old_content == new_content:
        return False

    try:
        conf_path.parent.mkdir(parents=True, exist_ok=True)
        conf_path.write_text(new_content)
    except OSError as exc:
        _log.warning("pw_quirks: could not write %s: %s", conf_path, exc)
        return False

    _log.info(
        "pw_quirks: applied ALSA headroom=%d quirk for %s (issue #105).",
        headroom, getattr(device_config, "name", "?"),
    )
    _restart_wireplumber()
    return True


def _remove_headroom_conf(conf_path: Path) -> bool:
    if not conf_path.exists():
        return False
    try:
        conf_path.unlink()
    except OSError as exc:
        _log.warning("pw_quirks: could not remove %s: %s", conf_path, exc)
        return False
    _log.info("pw_quirks: removed ALSA headroom quirk fragment (no longer needed).")
    _restart_wireplumber()
    return True


def _restart_wireplumber() -> None:
    from arctis_sound_manager import service_control as sc
    sc.restart("wireplumber", timeout=15)
