"""Single source of truth for the SteelSeries Arctis udev rules.

Both packaging (PKGBUILD / RPM spec / debian/rules → scripts/generate_udev_rules.py)
and the runtime CLI (asm-cli udev write-rules / dump-rules) call into this
module so the on-disk format is identical regardless of how the rules were
generated.
"""
from __future__ import annotations

from pathlib import Path
from typing import Iterable

from ruamel.yaml import YAML

_RULE_TEMPLATE = (
    'SUBSYSTEM=="usb", ATTRS{{idVendor}}=="{vid}", '
    'ATTRS{{idProduct}}=="{pid}", MODE="0666", TAG+="uaccess"'
)
_HEADER = '# Generated by Arctis Sound Manager'
_FOOTER_LABEL = 'LABEL="local_end"'


def _iter_yaml_files(paths: Iterable[Path]) -> Iterable[Path]:
    seen: set[Path] = set()
    for p in paths:
        if not p.is_dir():
            continue
        for f in sorted(p.glob('*.yaml')):
            real = f.resolve()
            if real in seen:
                continue
            seen.add(real)
            yield f


def load_devices(paths: Iterable[Path]) -> list[tuple[int, list[int], str]]:
    """Return [(vendor_id, [product_ids], name)] from every device YAML in *paths*.

    Later paths override earlier ones for the same (vendor_id, name) key, so the
    runtime DEVICES_CONFIG_FOLDER (HOME first, then SRC) keeps its current
    "user override wins" semantics, while packaging callers passing only the
    bundled SRC folder still get a deterministic order.
    """
    yaml = YAML(typ='safe')
    products: dict[tuple[int, str], tuple[int, list[int], str]] = {}
    for f in _iter_yaml_files(paths):
        data = yaml.load(f)
        device = data['device']
        vid = int(device['vendor_id'])
        pids = [int(p) for p in device['product_ids']]
        name = str(device['name'])
        products[(vid, name)] = (vid, pids, name)
    return list(products.values())


def render_rules(devices: list[tuple[int, list[int], str]]) -> str:
    """Render udev rules text from a list of (vendor_id, [pids], name) tuples."""
    lines: list[str] = [_HEADER, '', 'ACTION=="remove", GOTO="local_end"']
    for vid, pids, name in devices:
        lines.append('')
        lines.append(f'# {name}')
        for pid in pids:
            lines.append(_RULE_TEMPLATE.format(vid=f'{vid:04x}', pid=f'{pid:04x}'))
    lines += ['', _FOOTER_LABEL, '']
    return '\n'.join(lines)


def generate_rules(paths: Iterable[Path]) -> str:
    """Convenience: load + render in one call."""
    return render_rules(load_devices(paths))
