#!/usr/bin/env python3
"""Generate udev rules from device YAML files — writes to stdout.

Usage:
    python3 scripts/generate_udev_rules.py [devices_dir]

devices_dir defaults to src/arctis_sound_manager/devices/ relative to this script.
Used by the RPM spec and debian/rules during package build so rules are always
generated from the source of truth (device YAMLs) rather than hardcoded.
"""
import sys
from pathlib import Path

from ruamel.yaml import YAML


def main() -> None:
    if len(sys.argv) > 1:
        devices_dir = Path(sys.argv[1])
    else:
        devices_dir = Path(__file__).parent.parent / 'src' / 'arctis_sound_manager' / 'devices'

    if not devices_dir.is_dir():
        print(f'error: devices directory not found: {devices_dir}', file=sys.stderr)
        sys.exit(1)

    yaml = YAML(typ='safe')
    products: dict[tuple[int, str], tuple[int, list[int], str]] = {}

    for config_file in sorted(devices_dir.glob('*.yaml')):
        data = yaml.load(config_file)
        device = data['device']
        name: str = device['name']
        vendor_id: int = device['vendor_id']
        product_ids: list[int] = device['product_ids']
        key = (vendor_id, name)
        products[key] = (vendor_id, product_ids, name)

    rule_tmpl = 'SUBSYSTEM=="usb", ATTRS{{idVendor}}=="{vid}", ATTRS{{idProduct}}=="{pid}", MODE="0666", TAG+="uaccess"'
    lines = ['# Generated by Arctis Sound Manager', '', 'ACTION=="remove", GOTO="local_end"']

    for vendor_id, product_ids, name in products.values():
        lines.append('')
        lines.append(f'# {name}')
        for pid in product_ids:
            lines.append(rule_tmpl.format(vid=f'{vendor_id:04x}', pid=f'{pid:04x}'))

    lines += ['', 'LABEL="local_end"', '']
    sys.stdout.write('\n'.join(lines))


if __name__ == '__main__':
    main()
